name: Test Report

on:
  workflow_run:
    workflows: [Testing]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
      - name: Test report
        uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit