name: Testing

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode --update-snapshots verify

      - name: Test report
        uses: dorny/test-reporter@v1.5.0
        if: success()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: 'true'